### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined

### ISSUE THREAD

**Issue by rachelyoti** [vt5491/multi-theme-applicator#2]
I am getting the above error when selecting a local them using `shift-ctrl-v` vs 1.13.1 of atom.

**Comment by rachelyoti** [comment]
`TypeError: Cannot read property 'getElement' of undefined
    at Object.toggle (/Users//.atom/packages/multi-theme-applicator/lib/multi-theme-applicator.coffee:48:43)
    at HTMLSpanElement.dispatch (/Users//.atom/packages/multi-theme-applicator/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLSpanElement.elemData.handle (/Users//.atom/packages/multi-theme-applicator/node_modules/jquery/dist/jquery.js:4549:28)`

**Comment by vt5491** [comment]
Hi.  Thank for using MTA and posting an issue.

Yes, atom 1.13  [broke multi-theme-applicator](https://github.com/vt5491/multi-theme-applicator/issues/1)  .  They used to have a shadow dom feature, which I utilized for styling but they [removed it in 1.13](https://github.com/atom/atom/pull/12903), which caught me by surprise.

I am currently updating MTA to support 1.13, and I should have a 1.0 release available soon.  I have tested on windows and am currently testing on linux.

**Comment by vt5491** [comment]
I just made version 1.0.0 available.  I really need to test it more, but considering that the current version isn't working at all with atom 1.13, it's a definite improvement.

I added the capability to theme at various levels of scope: window, pane, file, and editor.  The old version basically only allowed for file level theming.  Just keep in mind, that because the CSS style sheets are no longer isolated behind a shadow dom, they can interfere with each other, that is to say applying a theme in one editor can affect the theme in another editor.  You're usually ok as long you theme everything at the same scope level, and only get in trouble if you start applying a hierarchy of themes e.g, atom-light at the window, then fairyfloss at the pane level, and then choco at the file level.  Then you can expect interference.

My intent is to provide a quick intro video in the ReadMe covering some the of the caveats, and how to properly use the "Remove theme button", and why I needed to add it.

**Comment by rachelyoti** [comment]
Ahh nice it seems to be working on my machine now. Good idea for a package, will make things easier when working with lots of files / different reops. Thanks.

**Comment by rachelyoti** [comment]
Hi - unfortunately the same error seems to have cropped up again:

`/Users/rachelblack/.atom/packages/multi-theme-applicator/lib/multi-theme-applicator.coffee:48
Hide Stack Trace
TypeError: Cannot read property 'getElement' of undefined
    at Object.toggle (/Users//.atom/packages/multi-theme-applicator/lib/multi-theme-applicator.coffee:48:43)
    at atom-workspace.cmdObj.multi-theme-applicator:toggle (/Users//.atom/packages/multi-theme-applicator/lib/multi-theme-applicator.coffee:23:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59) `

I updated to v 1.0.0 yesterday and it was working initially.

**Comment by vt5491** [comment]
hmm. ok.  I'm working on v 1.1.0 at the moment.  I'm using atom 1.13.1 with no problem.

What OS are you using (windows, linux, or mac)?

**Comment by vt5491** [comment]
Is it possible you were trying to style a non-editor, like the the "Settings" panel.  I once got this error when I tried to style a non-editor.  I will add a check to v 1.1.0 to check for this case.  

Otherwise, I would suggest resetting MTA by going to the command pallet (ctrl-shift-p), type "mta" to narrow down and select "Multi Theme Applicator Reset".  And then from atom menu select view->developer->Reload Windows ( or press ctrl-shift-f5), ( or simply restart atom).  This will clear out any prior themes.  Then you'll have to press ctrl-shift-v to re-apply themes.   Just make sure you don't do it against a non-editor panel until I can get v 1.1.0 out.

**Comment by vt5491** [comment]
Closing due to lack of activity.
